version: '3'

services:
  hub:
    image: "selenium/hub"
    expose:
      - "4444"

  chrome:
    image: selenium/node-chrome
    links:
    - selenium-hub:hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
    volumes:
    - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
